import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart'; // Keep for TextStyle potentially
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:macos_ui/macos_ui.dart';

import '../../domain/models/category.dart';
import '../providers/category_providers.dart';

/// A dialog for adding a new category or editing an existing one.
class AddEditCategoryDialog extends ConsumerStatefulWidget {
  /// The category to edit. If null, a new category is being added.
  final Category? categoryToEdit;

  const AddEditCategoryDialog({super.key, this.categoryToEdit});

  @override
  ConsumerState<AddEditCategoryDialog> createState() =>
      _AddEditCategoryDialogState();
}

class _AddEditCategoryDialogState extends ConsumerState<AddEditCategoryDialog> {
  // Removed _formKey as we are validating manually
  late TextEditingController _titleController;
  late TextEditingController _descriptionController;
  IconData _selectedIcon = CupertinoIcons.folder; // Default icon
  String? _titleError; // For manual validation message

  // Simple list of icons to choose from
  final List<IconData> _availableIcons = [
    CupertinoIcons.folder, CupertinoIcons.doc_text, CupertinoIcons.paintbrush,
    CupertinoIcons.lightbulb, CupertinoIcons.tag, CupertinoIcons.bookmark,
    CupertinoIcons.briefcase, CupertinoIcons.film, CupertinoIcons.music_note,
    CupertinoIcons.game_controller, CupertinoIcons.heart, CupertinoIcons.star,
    CupertinoIcons.cloud, CupertinoIcons.airplane, CupertinoIcons.car,
    CupertinoIcons.house,
    // Add more icons as needed
  ];

  @override
  void initState() {
    super.initState();
    _titleController =
        TextEditingController(text: widget.categoryToEdit?.title ?? '');
    _descriptionController =
        TextEditingController(text: widget.categoryToEdit?.description ?? '');
    _selectedIcon = widget.categoryToEdit?.icon ?? _availableIcons.first;
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _saveCategory() async {
    final title = _titleController.text.trim();
    final description = _descriptionController.text.trim();

    // Manual validation
    setState(() {
      if (title.isEmpty) {
        _titleError = 'Title cannot be empty';
      } else {
        _titleError = null;
      }
    });

    if (_titleError != null) {
      return; // Don't proceed if validation failed
    }

    final notifier = ref.read(categoryListProvider.notifier);
    final navigator = Navigator.of(context); // Capture navigator before async gap

    try {
      if (widget.categoryToEdit == null) {
        // Add new category
        final newCategory = Category(
          id: '', // ID will be generated by the repository
          title: title,
          description: description,
          icon: _selectedIcon,
        );
        await notifier.addCategory(newCategory);
      } else {
        // Update existing category
        final updatedCategory = Category(
          id: widget.categoryToEdit!.id,
          title: title,
          description: description,
          icon: _selectedIcon,
        );
        await notifier.updateCategory(updatedCategory);
      }
      navigator.pop(); // Close dialog on success
    } catch (error) {
      // TODO: Show error message to user (e.g., using another dialog or snackbar)
      print(widget.categoryToEdit == null
          ? 'Error adding category: $error'
          : 'Error updating category: $error');
      // Optionally show an error dialog here
      await showMacosAlertDialog(
        context: context,
        builder: (_) => MacosAlertDialog(
          appIcon: const MacosIcon(CupertinoIcons.exclamationmark_octagon),
          title: const Text('Error Saving Category'),
          message: Text('An unexpected error occurred: $error'),
          primaryButton: PushButton(
            controlSize: ControlSize.large,
            child: const Text('OK'),
            onPressed: () => Navigator.of(context).pop(),
          ),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return MacosAlertDialog(
      appIcon: MacosIcon(widget.categoryToEdit == null
          ? CupertinoIcons.add_circled
          : CupertinoIcons.pencil),
      title: Text(
        widget.categoryToEdit == null ? 'Add New Category' : 'Edit Category',
        style: MacosTheme.of(context).typography.headline,
      ),
      message: Column( // Wrap content in a Column for layout
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const SizedBox(height: 16),
          MacosTextField(
            controller: _titleController,
            placeholder: 'Category Title',
          ),
          if (_titleError != null) ...[
            const SizedBox(height: 4),
            Text(
              _titleError!,
              style: TextStyle(
                color: MacosColors.systemRedColor, // Use specific Macos color
                fontSize: 12,
              ),
            ),
          ],
          const SizedBox(height: 12),
          MacosTextField(
            controller: _descriptionController,
            placeholder: 'Description (optional)',
            maxLines: 3,
          ),
          const SizedBox(height: 16),
          Text('Select Icon:', style: MacosTheme.of(context).typography.body),
          const SizedBox(height: 8),
          Container( // Added container for better layout/scrolling if needed
            constraints: const BoxConstraints(maxHeight: 150), // Limit height
            child: SingleChildScrollView( // Allow scrolling for many icons
              child: Wrap(
                spacing: 8.0,
                runSpacing: 8.0,
                children: _availableIcons.map((icon) {
                  final isSelected = icon == _selectedIcon;
                  return MacosTooltip(
                    message: icon.toString(), // Basic tooltip
                    child: GestureDetector(
                      onTap: () {
                        setState(() {
                          _selectedIcon = icon;
                        });
                      },
                      child: Container(
                        padding: const EdgeInsets.all(6),
                        decoration: BoxDecoration(
                          color: isSelected
                              ? MacosTheme.of(context).primaryColor.withAlpha(77) // 0.3 opacity = ~77 alpha
                              : MacosTheme.of(context).canvasColor,
                          border: Border.all(
                            color: isSelected
                                ? MacosTheme.of(context).primaryColor
                                : MacosTheme.of(context).dividerColor,
                            width: isSelected ? 2.0 : 1.0,
                          ),
                          borderRadius: BorderRadius.circular(4),
                        ),
                        child: MacosIcon(icon, size: 24),
                      ),
                    ),
                  );
                }).toList(),
              ),
            ),
          ),
        ],
      ),
      primaryButton: PushButton(
        controlSize: ControlSize.large, // Correct parameter
        onPressed: _saveCategory,
        child: Text(widget.categoryToEdit == null ? 'Add' : 'Save'),
      ),
      // secondaryButton is optional in MacosAlertDialog, but good practice
      secondaryButton: PushButton(
        controlSize: ControlSize.large, // Correct parameter
        secondary: true,
        onPressed: () => Navigator.of(context).pop(),
        child: const Text('Cancel'),
      ),
    );
  }
}